  # [] [0|0]
Can_rx_sim_track_idType can_rx_sim_track_id
  # [] [0|0]
Can_rx_sim_statusType can_rx_sim_status
  # [m/s] [-32|31.75]
float64 can_rx_sim_range_rate
  # [m/s/s] [-32|31.75]
float64 can_rx_sim_range_accel
  # [m] [0|0]
int32 can_rx_sim_range
  # [m/s] [-32|31.75]
float64 can_rx_sim_lat_rate
  # [m] [-32|31.75]
float64 can_rx_sim_lat_pos
  # [] [0|0]
Can_rx_sim_functionType can_rx_sim_function
  # [deg] [-64|63.5]
float64 can_rx_sim_angle
