  # [] [0|0]
Can_tx_track_grouping_changedType can_tx_track_grouping_changed
  # [] [0|0]
Can_tx_track_oncomingType can_tx_track_oncoming
  # [] [-8|7.75]
float64 can_tx_track_lat_rate
  # [] [0|0]
Can_tx_track_bridge_objectType can_tx_track_bridge_object
  # [m] [0|7.5]
float64 can_tx_track_width
  # [] [0|7]
Can_tx_track_statusType can_tx_track_status
  # [] [0|1]
bool can_tx_track_rolling_count
  # [m/s] [-81.92|81.91]
float64 can_tx_track_range_rate
  # [m/s/s] [-25.6|25.55]
float64 can_tx_track_range_accel
  # [m] [0|204.7]
float64 can_tx_track_range
  # [] [0|3]
Can_tx_track_med_range_modeType can_tx_track_med_range_mode
  # [deg] [-51.2|51.1]
float64 can_tx_track_angle
