  # [] [0|0]
int32 can_tx_sw_version_dsp_3rd_byte
  # [] [0|0]
Can_tx_vertical_align_updatedType can_tx_vertical_align_updated
  # [] [-6|6]
float64 can_tx_vertical_misalignment
  # [] [0|255]
int32 can_tx_serv_align_updates_done
  # [] [0|0]
Can_tx_found_targetType can_tx_found_target
  # [deg] [-5|5]
float64 can_tx_factory_misalignment
  # [] [0|5]
Can_tx_factory_align_status_2Type can_tx_factory_align_status_2
  # [] [0|5]
Can_tx_factory_align_status_1Type can_tx_factory_align_status_1
  # [] [0|0]
Can_tx_recommend_unconvergeType can_tx_recommend_unconverge
  # [] [0|0]
int32 can_tx_wave_diff_a2d
  # [] [0|0]
Can_tx_system_power_modeType can_tx_system_power_mode
  # [] [0|0]
int32 can_tx_supply_n5v_a2d
  # [] [0|0]
int32 can_tx_supply_1p8v_a2d
