  # [] [0|0]
Can_tx_truck_target_detType can_tx_truck_target_det
  # [] [0|0]
Can_tx_lr_only_grating_lobe_detType can_tx_lr_only_grating_lobe_det
  # [] [0|0]
Can_tx_sidelobe_blockageType can_tx_sidelobe_blockage
  # [] [0|0]
Can_tx_partial_blockageType can_tx_partial_blockage
  # [] [0|0]
int32 can_tx_path_id_acc_stat
  # [] [0|3]
Can_tx_mr_lr_modeType can_tx_mr_lr_mode
  # [] [-8|7.9375]
float64 can_tx_auto_align_angle
  # [] [0|0]
int32 can_tx_rolling_count_3
  # [] [0|0]
int32 can_tx_path_id_fcw_stat
  # [] [0|0]
int32 can_tx_path_id_fcw_move
  # [] [0|0]
int32 can_tx_path_id_cmbb_stat
  # [] [0|0]
int32 can_tx_path_id_cmbb_move
  # [] [0|0]
int32 can_tx_path_id_acc
