  # [] [-16|15.875]
float64 can_tx_yaw_rate_bias
  # [] [0.9375|1.060546875]
float64 can_tx_veh_spd_comp_factor
  # [] [0|0]
int32 can_tx_sw_version_dsp
  # [degC] [-128|127]
int32 can_tx_temperature
  # [] [0|0]
modules_drivers_msgs/Can_tx_raw_data_modeType can_tx_raw_data_mode
  # [] [0|0]
modules_drivers_msgs/Can_tx_range_perf_errorType can_tx_range_perf_error
  # [] [0|0]
modules_drivers_msgs/Can_tx_overheat_errorType can_tx_overheat_error
  # [] [1|64]
int32 can_tx_maximum_tracks_ack
  # [] [0|0]
modules_drivers_msgs/Can_tx_internal_errorType can_tx_internal_error
  # [] [0|0]
modules_drivers_msgs/Can_tx_grouping_modeType can_tx_grouping_mode
  # [] [0|0]
modules_drivers_msgs/Can_tx_xcvr_operationalType can_tx_xcvr_operational
  # [deg] [0|2047]
int32 can_tx_steering_angle_ack
  # [] [0|0]
int32 can_tx_rolling_count_2
