  # [] [0|0]
Can_rx_steering_angle_validityType can_rx_steering_angle_validity
  # [deg/s] [0|2047]
int32 can_rx_steering_angle_rate
  # [] [0|0]
Can_rx_steering_angle_signType can_rx_steering_angle_sign
  # [] [0|0]
Can_rx_steering_angle_rate_signType can_rx_steering_angle_rate_sign
  # [deg] [0|2047]
int32 can_rx_steering_angle
  # [m] [-8192|8191]
int32 can_rx_radius_curvature
  # [] [0|0]
Can_rx_yaw_rate_validityType can_rx_yaw_rate_validity
  # [deg/s] [-128|127.9375]
float64 can_rx_yaw_rate
  # [] [0|0]
Can_rx_vehicle_speed_directionType can_rx_vehicle_speed_direction
  # [m/s] [0|127.9375]
float64 can_rx_vehicle_speed
