  # [] [0|0]
int32 can_rx_serv_align_updates_need
  # [] [0|0]
Can_rx_serv_align_typeType can_rx_serv_align_type
  # [] [0|0]
Can_rx_serv_align_enableType can_rx_serv_align_enable
  # [] [250|2000]
float64 can_rx_aalign_avg_ctr_total
  # [] [0|0]
Can_rx_auto_align_convergedType can_rx_auto_align_converged
  # [] [0|0]
Can_rx_auto_align_disableType can_rx_auto_align_disable
  # (+)clockwise [deg] [-8|7.9375]
float64 can_rx_angle_mounting_offset
  # [] [0|0]
Can_rx_wheel_slipType can_rx_wheel_slip
  # [cm] [0|125]
int32 can_rx_radar_height
  # [deg] [0|120]
int32 can_rx_radar_fov_mr
  # [deg] [0|30]
int32 can_rx_radar_fov_lr
  # [] [0|0]
Can_rx_long_accel_validityType can_rx_long_accel_validity
  # [m/s/s] [-8|7.96875]
float64 can_rx_long_accel
  # [] [0|0]
Can_rx_lat_accel_validityType can_rx_lat_accel_validity
  # [] [-8|7.96875]
float64 can_rx_lat_accel
