  # [] [0|0]
Can_rx_yaw_rate_bias_shiftType can_rx_yaw_rate_bias_shift
  # [] [0|31.875]
float64 can_rx_steering_gear_ratio
  # [cm] [200|710]
float64 can_rx_wheelbase
  # [cm] [200|710]
float64 can_rx_distance_rear_axle
  # [] [0|1.9921875]
float64 can_rx_cw_blockage_threshold
  # [m] [-2|10]
float64 can_rx_funnel_offset_right
  # [m] [-2|10]
float64 can_rx_funnel_offset_left
  # [deg] [0|6]
float64 can_rx_beamwidth_vert
  # [%] [-128|127]
int32 can_rx_oversteer_understeer
