  # [m] [-4000|3500]
float64 can_rx_volvo_short_track_roc
  # [] [0|0]
Can_rx_mr_only_transmitType can_rx_mr_only_transmit
  # [] [0|0]
Can_rx_lr_only_transmitType can_rx_lr_only_transmit
  # [deg] [-32|31]
int32 can_rx_high_yaw_angle
  # [] [0|0]
Can_rx_clear_faultsType can_rx_clear_faults
  # [] [0|0]
Can_rx_use_angle_misalignmentType can_rx_use_angle_misalignment
  # [] [0|0]
Can_rx_turn_signal_statusType can_rx_turn_signal_status
  # [] [0|0]
Can_rx_blockage_disableType can_rx_blockage_disable
  # [] [0|0]
Can_rx_vehicle_speed_validityType can_rx_vehicle_speed_validity
  # [] [0|1]
Can_rx_mmr_upside_downType can_rx_mmr_upside_down
  # [] [0|0]
Can_rx_wiper_statusType can_rx_wiper_status
  # [] [0|0]
Can_rx_raw_data_enableType can_rx_raw_data_enable
  # [] [0|0]
Can_rx_radar_cmd_radiateType can_rx_radar_cmd_radiate
  # [] [0|3]
Can_rx_grouping_modeType can_rx_grouping_mode
  # [] [1|64]
int32 can_rx_maximum_tracks
  # (+)to the right from driver's perspective [m] [-2|1.984375]
float64 can_rx_lateral_mounting_offset
  # (+)clockwise [deg] [-8|7.9375]
float64 can_rx_angle_misalignment
  # [] [0|65535]
int32 can_rx_scan_index_ack
