  # [m] [2|10]
float64 can_rx_fac_tgt_range_r2m
  # [m] [1|10]
float64 can_rx_fac_tgt_range_m2t
  # [m] [2|10]
float64 can_rx_fac_tgt_range_1
  # [cm] [-100|100]
int32 can_rx_fac_tgt_mtg_space_ver
  # [cm] [-100|100]
int32 can_rx_fac_tgt_mtg_space_hor
  # [cm] [-100|100]
int32 can_rx_fac_tgt_mtg_offset
  # [] [0|100]
int32 can_rx_fac_align_samp_req
  # [] [0|100]
int32 can_rx_fac_align_max_nt
  # [] [0|0]
Can_rx_fac_align_cmd_2Type can_rx_fac_align_cmd_2
  # [] [0|0]
Can_rx_fac_align_cmd_1Type can_rx_fac_align_cmd_1
