uint32 number_of_discrete_graph_t  #  optional 
uint32 spline_order  #  optional 
float64 speed_kernel_weight #  optional 
float64 accel_kernel_weight  #  optional 
float64 jerk_kernel_weight  #  optional 
float64 follow_weight  #  optional 
float64 stop_weight   #  optional 
float64 cruise_weight   #  optional 
float64 regularization_weight  # [ default = 0.1 ]#  optional 
float64 follow_drag_distance  #  optional 
