#next ID: 11
float64 total_path_length #[ default = 200.0 ]   optional 
float64 total_time # [ default = 6.0 ]   optional 
float64 preferred_max_acceleration #[ default = 1.2 ]   optional 
float64 preferred_min_deceleration # [ default = -1.8 ]   optional 
float64 max_acceleration #[ default = 2.0 ]   optional 
float64 min_deceleration #[ default = -4.5 ]   optional 

QpSplineConfig qp_spline_config #  optional 
QpPiecewiseConfig qp_piecewise_config #   optional 
StBoundaryConfig st_boundary_config #   optional 
