################################ 
# The start_s and end_s are longitudinal values.
# start_s <= end_s.
#
#              end_s
#                ^
#                |
#          S  direction
#                |
#            start_s
#
# The start_l and end_l are lateral values.
# start_l <= end_l. Left side of the reference line is positive,
# and right side of the reference line is negative.
#  end_l  <-----L direction---- start_l
################################ 


float64 start_s #  optional 
float64 end_s #  optional 
float64 start_l #  optional 
float64 end_l #  optional 

