string name #  optional 
float64[] sampled_s  
float64[] static_obstacle_lower_bound  
float64[] dynamic_obstacle_lower_bound  
float64[] static_obstacle_upper_bound  
float64[] dynamic_obstacle_upper_bound  
float64[] map_lower_bound  
float64[] map_upper_bound  
modules_common_msgs/SLPoint sl_path  
float64[] aggregated_boundary_s  
float64[] aggregated_boundary_low  
float64[] aggregated_boundary_high  
