
modules_canbus_msgs/ChassisDetailType car_type               # car type
modules_canbus_msgs/BasicInfo basic             # basic info
modules_canbus_msgs/Safety safety               # safety
modules_canbus_msgs/Gear gear                   # gear
modules_canbus_msgs/Ems ems                     # engine manager system
modules_canbus_msgs/Esp esp                     # Electronic Stability Program
modules_canbus_msgs/Gas gas                     # gas pedal
modules_canbus_msgs/Epb epb                     # Electronic parking brake
modules_canbus_msgs/Brake brake                 # brake pedal
modules_canbus_msgs/Deceleration deceleration   # deceleration
modules_canbus_msgs/VehicleSpd vehicle_spd      # vehicle speed
modules_canbus_msgs/Eps eps                     # Electronic Power Steering
modules_canbus_msgs/Light light                 # Light
modules_canbus_msgs/Battery battery             # Battery info
modules_canbus_msgs/CheckResponseSignal check_response
modules_canbus_msgs/License license             # License info
