#Standard deviation of position, east/north/up in meters.
modules_common_msgs/Point3D position_std_dev

#Standard deviation of quaternion qx/qy/qz, unitless.
modules_common_msgs/Point3D orientation_std_dev 

#Standard deviation of linear velocity, east/north/up in meters per second.
modules_common_msgs/Point3D linear_velocity_std_dev 

#Standard deviation of linear acceleration, right/forward/up in meters per
#square second.
modules_common_msgs/Point3D linear_acceleration_std_dev 

#Standard deviation of angular velocity, right/forward/up in radians per
#second.
modules_common_msgs/Point3D angular_velocity_std_dev 

#TODO: Define covariance items when needed.
